version: "3.9"
services:
  rabbitmq:
    container_name: "rabbitMq-Twitter"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=twitter
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8084:8080"